[package]
name = "highway"
version = "0.1.0"
authors = ["Jens Reidel <adrian@travitia.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
tokio-tungstenite = { version = "0.13", default-features = false, features = ["connect"] }
base64 = "0.13"
bytes = "1.0"
env_logger = { version = "0.8", default-features = false, features = [
    "termcolor",
    "atty",
    "humantime"
] }
hyper = { version = "0.14", features = ["client", "server", "http1", "tcp"] }
lazy_static = "1.4"
leaky-bucket-lite = "0.1"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
simd-json = { version = "0.3", default-features = false, features = [
    "allow-non-simd",
    "known-key",
    "neon",
    "serde_impl"
], optional = true }
tokio = { version = "1.1", default-features = false, features = [
    "rt-multi-thread",
    "macros"
] }
futures-util = "0.3"
qstring = "0.7"
sha-1 = "0.9"

[features]
simd = ["simd-json"]

[profile.release]
codegen-units = 1
debug = false
incremental = false
lto = true
opt-level = 3
panic = "abort"
